### ISSUE TITLE
Build is broke on OSx

### ISSUE THREAD

**Issue by rmcgurrin** [BBN-Q/libaps2#73]
Can't build.  Get these errors:
'''
/Users/rmcgurrin/sandbox/q/libaps2/test/test_CSR.cpp:23:7: error: no type named 'random_device' in namespace 'std'
        std::random_device rd;
        ~~~~~^
/Users/rmcgurrin/sandbox/q/libaps2/test/test_CSR.cpp:24:7: error: no member named 'default_random_engine' in namespace 'std'
        std::default_random_engine engine(rd());
        ~~~~~^
/Users/rmcgurrin/sandbox/q/libaps2/test/test_CSR.cpp:72:8: error: no template named 'uniform_real_distribution' in namespace 'std'; did you
      mean 'uniform_int_distribution'?
                std::uniform_real_distribution<double> trigger_dist(0, 1.0);
                ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
                     uniform_int_distribution
...
'''

Issue was introduced in 9082a7c5873b87 with test_CSR.cpp

**Comment by caryan** [comment]
Closed by #74
